### ISSUE TITLE
Skjulte Skatter of April is not available in Norwegian, only in Norwegian

### ISSUE THREAD

**Issue by Ghostbird** [bcc-code/bcc-literature#160] opened 2022-04-21 21:15 UTC
Yeah, it's as weird as the title says. If I go to https://literature.bcc.no/books/1/2022/4?lang=no I see:
![Screenshot_20220421-210521](https://user-images.githubusercontent.com/1202149/164552381-92b9cf09-c1d6-44a9-a71a-a9f84a88f199.png)
The link I see there redirects me to this same page.

The only seemingly incorrect thing I've noticed is that the URI says `lang=no` which isn't a standard language code AFAIK. It might be a lowercased version of the country code NO for Norway. I guess this makes sense in a way SSSF doesn't publish separately in Nynorsk and Bokmål, they just publish content meant for Norway.

**Comment by cs1m0n** [comment] 2022-11-17 07:49
Can't reproduce it, but most probably fixed by [this commit](https://github.com/bcc-code/bcc-literature/commit/4c34bfd944e387e23359d7c074ac9b8ee8d5a4b4).

**Closed by cs1m0n** 2022-11-17 07:49 UTC
